# Generated by Django 3.1 on 2021-06-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='Opisanii',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
    ]
